In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("Restaurant_Reviews.tsv", delimiter="\t", quoting=3)
dataset.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
Review    1000 non-null object
Liked     1000 non-null int64
dtypes: int64(1), object(1)
memory usage: 11.8+ KB


In [4]:
dataset.dtypes

Review    object
Liked      int64
dtype: object

In [5]:
dataset.groupby('Liked').size()

Liked
0    500
1    500
dtype: int64

In [6]:
dataset.isnull().sum()

Review    0
Liked     0
dtype: int64

In [7]:
dataset['Review'][0]

'Wow... Loved this place.'

In [8]:
# Removing Numbers and Punctuations
import re
review = re.sub( '[^a-zA-Z]', ' ', dataset['Review'][0] )
print(review)

Wow    Loved this place 


In [9]:
review = review.lower()
review

'wow    loved this place '

In [10]:
import nltk
# nltk.download('stopwords')

In [11]:
from nltk.corpus import stopwords

In [12]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [13]:
len(stopwords.words('english'))

179

In [14]:
review

'wow    loved this place '

In [15]:
review = review.split()
review

['wow', 'loved', 'this', 'place']

In [16]:
review1 = [ word for word in review if not word in set(stopwords.words('english')) ]
review1

['wow', 'loved', 'place']

In [17]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
review1 = [ ps.stem(word) for word in review1 ]
review1

['wow', 'love', 'place']

In [18]:
review2 = ' '.join(review1)
review2

'wow love place'

In [19]:
corpus1 = []
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=3)
print(review2)
corpus1.append(review2)
print(corpus1)
X = cv.fit_transform(corpus1)
print(X.toarray())

wow love place
['wow love place']
[[1 1 1]]


In [20]:
dataset.shape

(1000, 2)

In [21]:
dataset.tail()

Review  Liked
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

In [22]:
import re
import nltk
# nltk.download('stopwords')
from nltk.stem.porter import PorterStemmer

corpus = []
for i in range(0,1000):
    review = re.sub('[^a-zA-Z]',' ',dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ ps.stem(word) for word in review if not word in set(stopwords.words('english')) ]
    review = ' '.join(review)
    print(review)
    corpus.append(review)

wow love place
crust good
tasti textur nasti
stop late may bank holiday rick steve recommend love
select menu great price
get angri want damn pho
honeslti tast fresh
potato like rubber could tell made ahead time kept warmer
fri great
great touch
servic prompt
would go back
cashier care ever say still end wayyy overpr
tri cape cod ravoli chicken cranberri mmmm
disgust pretti sure human hair
shock sign indic cash
highli recommend
waitress littl slow servic
place worth time let alon vega
like
burritto blah
food amaz
servic also cute
could care less interior beauti
perform
right red velvet cake ohhh stuff good
never brought salad ask
hole wall great mexican street taco friendli staff
took hour get food tabl restaur food luke warm sever run around like total overwhelm
worst salmon sashimi
also combo like burger fri beer decent deal
like final blow
found place accid could happier
seem like good quick place grab bite familiar pub food favor look elsewher
overal like place lot
redeem qualiti r

pizza good peanut sauc tasti
tabl servic pretti fast
fantast servic
well would given godfath zero star possibl
know make
tough short flavor
hope place stick around
bar vega ever recal charg tap water
restaur atmospher exquisit
good servic clean inexpens boot
seafood fresh gener portion
plu buck
servic par either
thu far visit twice food absolut delici time
good year ago
self proclaim coffe cafe wildli disappoint
veggitarian platter world
cant go wrong food
beat
stop place madison ironman friendli kind staff
chef friendli good job
better dedic boba tea spot even jenni pho
like patio servic outstand
goat taco skimp meat wow flavor
think
mac salad pretti bland get
went bachi burger friend recommend disappoint
servic stink
wait wait
place qualiti sushi qualiti restaur
would definit recommend wing well pizza
great pizza salad
thing went wrong burn saganaki
wait hour breakfast could done time better home
place amaz
hate disagre fellow yelper husband disappoint place
wait hour never got eithe

oh thing beauti restaur
gone go
greasi unhealthi meal
first time might last
burger amaz
similarli deliveri man say word apolog food minut late
way expens
sure order dessert even need pack go tiramisu cannoli die
first time wait next
bartend also nice
everyth good tasti
place two thumb way
best place vega breakfast check sat sun
love authent mexican food want whole bunch interest yet delici meat choos need tri place
terribl manag
excel new restaur experienc frenchman
zero star would give zero star
great steak great side great wine amaz dessert
worst martini ever
steak shrimp opinion best entre gc
opportun today sampl amaz pizza
wait thirti minut seat although vacant tabl folk wait
yellowtail carpaccio melt mouth fresh
tri go back even empti
go eat potato found stranger hair
spici enough perfect actual
last night second time dine happi decid go back
even hello right
dessert bit strang
boyfriend came first time recent trip vega could pleas qualiti food servic
realli recommend place go wro

great atmospher friendli fast servic
receiv pita huge lot meat thumb
food arriv meh
pay hot dog fri look like came kid meal wienerschnitzel idea good meal
classic main lobster roll fantast
brother law work mall ate day guess sick night
good go review place twice herea tribut place tribut event held last night
chip salsa realli good salsa fresh
place great
mediocr food
get insid impress place
super pissd
servic super friendli
sad littl veget overcook
place nice surpris
golden crispi delici
high hope place sinc burger cook charcoal grill unfortun tast fell flat way flat
could eat bruschetta day devin
singl employe came see ok even need water refil final serv us food
lastli mozzarella stick best thing order
first time ever came amaz experi still tell peopl awesom duck
server neglig need made us feel unwelcom would suggest place
servic terribl though
place overpr consist boba realli overpr
pack
love place
say dessert yummi
food terribl
season fruit fresh white peach pure
kept get wors wors

In [23]:
type(review)

str

In [24]:
corpus

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt',
 'would go back',
 'cashier care ever say still end wayyy overpr',
 'tri cape cod ravoli chicken cranberri mmmm',
 'disgust pretti sure human hair',
 'shock sign indic cash',
 'highli recommend',
 'waitress littl slow servic',
 'place worth time let alon vega',
 'like',
 'burritto blah',
 'food amaz',
 'servic also cute',
 'could care less interior beauti',
 'perform',
 'right red velvet cake ohhh stuff good',
 'never brought salad ask',
 'hole wall great mexican street taco friendli staff',
 'took hour get food tabl restaur food luke warm sever run around like total overwhelm',
 'worst salmon sashimi',
 'also combo like burger fri beer decent deal',
 'like final blow',
 'found place acc

In [25]:
type(corpus)

list

In [26]:
corpus_dataset = pd.DataFrame(corpus)
corpus_dataset.head()

0
0                                     wow love place
1                                         crust good
2                                 tasti textur nasti
3  stop late may bank holiday rick steve recommen...
4                            select menu great price

In [27]:
corpus_dataset['corpus'] = corpus_dataset
corpus_dataset.head()

0  \
0                                     wow love place   
1                                         crust good   
2                                 tasti textur nasti   
3  stop late may bank holiday rick steve recommen...   
4                            select menu great price   

                                              corpus  
0                                     wow love place  
1                                         crust good  
2                                 tasti textur nasti  
3  stop late may bank holiday rick steve recommen...  
4                            select menu great price

In [28]:
corpus_dataset = corpus_dataset.drop([0], axis=1)
corpus_dataset.head()

corpus
0                                     wow love place
1                                         crust good
2                                 tasti textur nasti
3  stop late may bank holiday rick steve recommen...
4                            select menu great price

In [29]:
corpus_dataset.to_csv("corpus_dataset.csv")

In [30]:
type(corpus_dataset)

pandas.core.frame.DataFrame

In [31]:
# Create a Bag of Words Model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)

In [32]:
X = cv.fit_transform(corpus).toarray()
X[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
dataset.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [35]:
cv.get_feature_names()

['absolut',
 'absolutley',
 'accid',
 'accommod',
 'accomod',
 'accordingli',
 'account',
 'ach',
 'acknowledg',
 'across',
 'actual',
 'ad',
 'afford',
 'afternoon',
 'ago',
 'ahead',
 'airlin',
 'airport',
 'ala',
 'albondiga',
 'allergi',
 'almond',
 'almost',
 'alon',
 'also',
 'although',
 'alway',
 'amaz',
 'ambianc',
 'ambienc',
 'amount',
 'ampl',
 'andddd',
 'angri',
 'annoy',
 'anoth',
 'anticip',
 'anymor',
 'anyon',
 'anyth',
 'anytim',
 'anyway',
 'apart',
 'apolog',
 'app',
 'appal',
 'appar',
 'appeal',
 'appet',
 'appetit',
 'appl',
 'approv',
 'area',
 'arepa',
 'aria',
 'around',
 'array',
 'arriv',
 'articl',
 'ask',
 'assur',
 'ate',
 'atmospher',
 'atroci',
 'attach',
 'attack',
 'attent',
 'attitud',
 'auju',
 'authent',
 'averag',
 'avocado',
 'avoid',
 'aw',
 'away',
 'awesom',
 'awkward',
 'awkwardli',
 'ayc',
 'az',
 'baba',
 'babi',
 'bachi',
 'back',
 'bacon',
 'bad',
 'bagel',
 'bakeri',
 'baklava',
 'ball',
 'bamboo',
 'banana',
 'bank',
 'bar',
 'bare',
 

In [36]:
len(cv.get_feature_names())

1500

In [37]:
y = dataset.iloc[:,1].values
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [39]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [40]:
y_pred = classifier.predict(X_test)

In [41]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [42]:
confusion_matrix(y_test,y_pred)

array([[55, 42],
       [12, 91]], dtype=int64)

In [43]:
accuracy_score(y_test,y_pred)

0.73

In [44]:
Review = "nice service"
input1 = [Review]

input_data = cv.transform(input1).toarray()

input_pred = classifier.predict(input_data)

if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Positive


In [45]:
Review = "long waiting time"
input1 = [Review]

input_data = cv.transform(input1).toarray()

input_pred = classifier.predict(input_data)

if input_pred[0]==1:
    print("Review is Positive")
else:
    print("Review is Negative")

Review is Negative
